replicaCount: 2
image:
  repository: fastapi-app
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: fastapi.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
